-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 16:47:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stock_info
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stock_info
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stock_info` DEFAULT CHARACTER SET utf8 ;
USE `stock_info` ;

-- -----------------------------------------------------
-- Table `stock_info`.`Transient_Data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_info`.`Transient_Data` (
  `central_index_key` INT NOT NULL,
  `fiscal_year_end_month` VARCHAR(10) NOT NULL,
  `latest_quarter_date` DATE NOT NULL,
  `market_capital` INT NOT NULL,
  `EBITDA` INT NOT NULL,
  `pe_ratio` DOUBLE NOT NULL,
  `peg_ratio` DOUBLE NOT NULL,
  `book_value` DOUBLE NOT NULL,
  `dividend_per_share` DOUBLE NULL,
  `dividend_yield` DOUBLE NULL,
  `eps` DOUBLE NOT NULL,
  `revenue_per_share_ttm` DOUBLE NOT NULL,
  `profit_margin` DOUBLE NOT NULL,
  `operating_margin_ttm` DOUBLE NOT NULL,
  `return_on_assets_ttm` DOUBLE NOT NULL,
  `return_on_equity_ttm` DOUBLE NOT NULL,
  `revenue_ttm` INT NOT NULL,
  `gross_profit_ttm` INT NOT NULL,
  `diluted_epsttm` DOUBLE NOT NULL,
  `quarterly_earnings_growth_yoy` DOUBLE NOT NULL,
  `quarterly_revenue_growth_yoy` DOUBLE NOT NULL,
  `analyst_target_price` DOUBLE NULL,
  `trailing_pe` DOUBLE NOT NULL,
  `forward_pe` DOUBLE NOT NULL,
  `price_to_sales_ratio_ttm` DOUBLE NOT NULL,
  `price_to_book_ratio` DOUBLE NOT NULL,
  `ev_to_revenue` DOUBLE NOT NULL,
  `ev_to_ebitda` DOUBLE NOT NULL,
  `beta` DOUBLE NOT NULL,
  `52_week_high` DOUBLE NOT NULL,
  `52_week_low` DOUBLE NOT NULL,
  `200_day_moving_average` DOUBLE NOT NULL,
  `shares_outstanding` INT NOT NULL,
  `dividend_date` DATE NOT NULL,
  `ex_dividend_date` DATE NOT NULL,
  `last_retrieval_time` DATETIME NOT NULL,
  `price_history_five_year` BLOB NOT NULL,
  PRIMARY KEY (`central_index_key`),
  UNIQUE INDEX `central_index_key_UNIQUE` (`central_index_key` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stock_info`.`Fixed_Info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stock_info`.`Fixed_Info` (
  `central_index_key` INT NOT NULL,
  `symbol` VARCHAR(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `asset_type` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `exchange` VARCHAR(10) NOT NULL,
  `currency` VARCHAR(5) NOT NULL,
  `country` VARCHAR(30) NOT NULL,
  `sector` VARCHAR(45) NOT NULL,
  `industry` VARCHAR(45) NOT NULL,
  `address_state` VARCHAR(2) NULL,
  `address_city` VARCHAR(45) NOT NULL,
  `address_country` VARCHAR(30) NOT NULL,
  `address_street` VARCHAR(60) NULL,
  `fiscal_year_end_month` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`central_index_key`),
  UNIQUE INDEX `central_index_key_UNIQUE` (`central_index_key` ASC) VISIBLE,
  CONSTRAINT `symbol`
    FOREIGN KEY (`central_index_key`)
    REFERENCES `stock_info`.`Transient_Data` (`central_index_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;